#define FLOW_TAP_TERM 125
#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 175
#define QUICK_TAP_TERM 150

#define ONESHOT_TIMEOUT 3000
#define ONESHOT_TAP_TOGGLE 2
#define ONESHOT_ALLOW_USER_INTERACTION
#define ONESHOT_PRESS_HOTKEYS

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 14

#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "7Dely/Vq740r"
#define LAYER_STATE_8BIT

#define NAVIGATOR_SCROLL_DIVIDER 50

#define AUTOMOUSE_LAYER 3
#define AUTOMOUSE_TIMEOUT 1
#define AUTOMOUSE_THRESHOLD 20
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define NAVIGATOR_TRACKBALL_ROTATION 35
#define RGB_MATRIX_STARTUP_SPD 60

