#define FLOW_TAP_TERM 125
#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 150

#define ONESHOT_TAP_TOGGLE 2

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 3000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 14

#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "7Dely/Xb3LPB"
#define LAYER_STATE_8BIT

#define NAVIGATOR_SCROLL_DIVIDER 50

#define AUTOMOUSE_LAYER 4
#define AUTOMOUSE_TIMEOUT 1
#define AUTOMOUSE_THRESHOLD 20
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define NAVIGATOR_TRACKBALL_ROTATION 26
#define RGB_MATRIX_STARTUP_SPD 60

